[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"
authors = ["Rafli Putra"]

[lib]
path = "src/lib.rs"

[dependencies]
actix-web = "4.9.0"
tokio = {version = "1.41.1", features = ["macros", "rt-multi-thread"]}

[dev-dependencies]
reqwest = "0.12.9"